const STATUS = {
  EMPLOYED: 'employed',
  UNEMPLOYED: 'unemployed',
  EDUCATION: 'education',
  ENTREPRENEURSHIP: 'entrepreneurship',
  NEET: 'neet',
  NEEDS_CLARIFICATION: 'needs_clarification',
};

const MAHALLAS = [
  "Yangi hayot",
  "Bog'ishamol",
  "Universitet",
  "Do'stlik",
  "Zarnigor",
  "Qo'yliq",
  "Olmazar",
];

const SUPPORT_TYPES = {
  EMPLOYMENT: 'employment',
  VOCATIONAL: 'vocational',
  EDUCATION: 'education',
  ENTREPRENEURSHIP: 'entrepreneurship',
  PSYCHOLOGICAL: 'psychological',
  CLARIFICATION: 'clarification',
};

const youthProfiles = [
  {
    id: 'Y001',
    fullName: 'Aliyev Jasur Baxtiyorovich',
    age: 22,
    gender: 'male',
    mahalla: 'Yangi hayot',
    status: STATUS.EMPLOYED,
    occupation: "Dasturchi — TechSoft MChJ",
    education: "Oliy (TATU, 2023-yil bitiruvchi)",
    phone: '+998 9X XXX XX 01',
    lastUpdated: '2026-08-01',
    needsSupport: false,
    supportTypes: [],
    history: [
      { date: '2026-01-10', status: STATUS.UNEMPLOYED, note: "Universitetni tamomlab, ishsiz qoldi" },
      { date: '2026-04-05', status: STATUS.EMPLOYED, note: "TechSoft MChJga dasturchi sifatida ishga kirdi" },
    ],
  },
  {
    id: 'Y002',
    fullName: 'Yusupova Dilnoza Hamidovna',
    age: 19,
    gender: 'female',
    mahalla: "Bog'ishamol",
    status: STATUS.EDUCATION,
    occupation: null,
    education: "Oliy (NUUz, 3-kurs, Filologiya)",
    phone: '+998 9X XXX XX 02',
    lastUpdated: '2026-07-20',
    needsSupport: false,
    supportTypes: [],
    history: [
      { date: '2025-09-01', status: STATUS.EDUCATION, note: "NUUzga qabul qilindi" },
    ],
  },
  {
    id: 'Y003',
    fullName: 'Karimov Sherzod Ulmasovich',
    age: 24,
    gender: 'male',
    mahalla: 'Universitet',
    status: STATUS.UNEMPLOYED,
    occupation: null,
    education: "O'rta maxsus (Qurilish texnikumi, 2024)",
    phone: '+998 9X XXX XX 03',
    lastUpdated: '2026-08-05',
    needsSupport: true,
    supportTypes: [SUPPORT_TYPES.EMPLOYMENT, SUPPORT_TYPES.VOCATIONAL],
    history: [
      { date: '2024-06-15', status: STATUS.UNEMPLOYED, note: "Texnikumni tamomlab, qurilish sohasida ish qidirmoqda" },
      { date: '2026-02-10', status: STATUS.UNEMPLOYED, note: "Mehnat birjasida ro'yxatdan o'tdi, hali joylashmadi" },
    ],
  },
  {
    id: 'Y004',
    fullName: 'Toshmatova Feruza Aliyevna',
    age: 21,
    gender: 'female',
    mahalla: "Do'stlik",
    status: STATUS.ENTREPRENEURSHIP,
    occupation: "Meva-sabzavot savdosi — shaxsiy tadbirkorlik",
    education: "O'rta (Umumta'lim maktabi, 2023)",
    phone: '+998 9X XXX XX 04',
    lastUpdated: '2026-07-28',
    needsSupport: false,
    supportTypes: [],
    history: [
      { date: '2023-06-01', status: STATUS.UNEMPLOYED, note: "Maktabni tamomlab ishsiz qoldi" },
      { date: '2024-03-15', status: STATUS.ENTREPRENEURSHIP, note: "Tadbirkorlik grantini oldi, bozorda savdo boshladi" },
    ],
  },
  {
    id: 'Y005',
    fullName: 'Nazarov Bobur Shamsiyevich',
    age: 23,
    gender: 'male',
    mahalla: 'Zarnigor',
    status: STATUS.NEET,
    occupation: null,
    education: "O'rta (Umumta'lim maktabi, 2021)",
    phone: '+998 9X XXX XX 05',
    lastUpdated: '2026-06-15',
    needsSupport: true,
    supportTypes: [SUPPORT_TYPES.EMPLOYMENT, SUPPORT_TYPES.VOCATIONAL, SUPPORT_TYPES.PSYCHOLOGICAL],
    history: [
      { date: '2021-06-01', status: STATUS.UNEMPLOYED, note: "Maktabni tamomlab, ta'lim yoki ishga kirmadi" },
      { date: '2022-09-01', status: STATUS.EDUCATION, note: "Texnikumga kirdi" },
      { date: '2023-01-15', status: STATUS.NEET, note: "Texnikumdan chiqdi, hech qanday faoliyat yo'q" },
    ],
  },
  {
    id: 'Y006',
    fullName: 'Rahimova Mohira Bahromovna',
    age: 20,
    gender: 'female',
    mahalla: "Qo'yliq",
    status: STATUS.EDUCATION,
    occupation: null,
    education: "Oliy (TDIU, 2-kurs, Iqtisodiyot)",
    phone: '+998 9X XXX XX 06',
    lastUpdated: '2026-08-08',
    needsSupport: false,
    supportTypes: [],
    history: [
      { date: '2024-09-01', status: STATUS.EDUCATION, note: "TDIU iqtisodiyot fakultetiga qabul qilindi" },
    ],
  },
  {
    id: 'Y007',
    fullName: 'Ergashev Timur Bekzodovich',
    age: 25,
    gender: 'male',
    mahalla: 'Olmazar',
    status: STATUS.EMPLOYED,
    occupation: "Elektr ustasi — Qurilish+ AJ",
    education: "O'rta maxsus (Elektrotexnika KHM, 2022)",
    phone: '+998 9X XXX XX 07',
    lastUpdated: '2026-07-30',
    needsSupport: false,
    supportTypes: [],
    history: [
      { date: '2022-06-01', status: STATUS.UNEMPLOYED, note: "KHMni tamomlab, ish qidirdi" },
      { date: '2022-09-10', status: STATUS.EMPLOYED, note: "Qurilish kompaniyasiga ishga kirdi" },
    ],
  },
  {
    id: 'Y008',
    fullName: 'Pulatova Sarvinoz Ismoilovna',
    age: 18,
    gender: 'female',
    mahalla: 'Yangi hayot',
    status: STATUS.NEEDS_CLARIFICATION,
    occupation: null,
    education: "Noma'lum",
    phone: '+998 9X XXX XX 08',
    lastUpdated: '2026-05-20',
    needsSupport: true,
    supportTypes: [SUPPORT_TYPES.CLARIFICATION],
    history: [
      { date: '2026-05-20', status: STATUS.NEEDS_CLARIFICATION, note: "Ma'lumotlar yangilanmagan, aniqlashtirish talab qilinadi" },
    ],
  },
  {
    id: 'Y009',
    fullName: 'Xolmatov Sanjar Iskandarovich',
    age: 26,
    gender: 'male',
    mahalla: "Bog'ishamol",
    status: STATUS.ENTREPRENEURSHIP,
    occupation: "IT konsulting — shaxsiy xizmat",
    education: "Oliy (TATU, Dasturiy ta'minot, 2022)",
    phone: '+998 9X XXX XX 09',
    lastUpdated: '2026-08-10',
    needsSupport: false,
    supportTypes: [],
    history: [
      { date: '2022-06-01', status: STATUS.UNEMPLOYED, note: "Universitetni tamomlab ishsiz" },
      { date: '2023-03-01', status: STATUS.EMPLOYED, note: "IT kompaniyada ishladi" },
      { date: '2024-07-01', status: STATUS.ENTREPRENEURSHIP, note: "Shaxsiy IT konsalting biznesini ochdi" },
    ],
  },
  {
    id: 'Y010',
    fullName: 'Abdullayeva Zulfiya Nurullayevna',
    age: 22,
    gender: 'female',
    mahalla: 'Universitet',
    status: STATUS.UNEMPLOYED,
    occupation: null,
    education: "Oliy (NUUz, Jurnalistika, 2025)",
    phone: '+998 9X XXX XX 10',
    lastUpdated: '2026-07-25',
    needsSupport: true,
    supportTypes: [SUPPORT_TYPES.EMPLOYMENT],
    history: [
      { date: '2025-07-01', status: STATUS.UNEMPLOYED, note: "Universitetni tamomlab, media sohasida ish qidirmoqda" },
      { date: '2026-02-15', status: STATUS.UNEMPLOYED, note: "Bir nechta murojaat qilindi, hali joylashmadi" },
    ],
  },
  {
    id: 'Y011',
    fullName: 'Mirzayev Doniyor Hamzayevich',
    age: 20,
    gender: 'male',
    mahalla: "Do'stlik",
    status: STATUS.NEET,
    occupation: null,
    education: "O'rta (Umumta'lim maktabi, 2024)",
    phone: '+998 9X XXX XX 11',
    lastUpdated: '2026-06-30',
    needsSupport: true,
    supportTypes: [SUPPORT_TYPES.EDUCATION, SUPPORT_TYPES.VOCATIONAL, SUPPORT_TYPES.PSYCHOLOGICAL],
    history: [
      { date: '2024-06-01', status: STATUS.UNEMPLOYED, note: "Maktabni tamomlab, ta'lim yoki ish bilan band emas" },
      { date: '2026-01-20', status: STATUS.NEET, note: "18 oydan ortiq hech qanday faoliyat yo'q, diqqat talab qilinadi" },
    ],
  },
  {
    id: 'Y012',
    fullName: "Qosimova Malika Farhod qizi",
    age: 23,
    gender: 'female',
    mahalla: 'Zarnigor',
    status: STATUS.EMPLOYED,
    occupation: "Tibbiy hamshira — Tuman markaziy poliklinikasi",
    education: "O'rta maxsus (Tibbiyot kolleji, 2023)",
    phone: '+998 9X XXX XX 12',
    lastUpdated: '2026-08-05',
    needsSupport: false,
    supportTypes: [],
    history: [
      { date: '2023-07-01', status: STATUS.UNEMPLOYED, note: "Kollejni tamomlab ish qidirdi" },
      { date: '2023-10-01', status: STATUS.EMPLOYED, note: "Poliklinikaga hamshira sifatida qabul qilindi" },
    ],
  },
  {
    id: 'Y013',
    fullName: 'Umarov Firdavs Mansurovich',
    age: 28,
    gender: 'male',
    mahalla: "Qo'yliq",
    status: STATUS.EMPLOYED,
    occupation: "Bosh hisobchi — Savdo Invest MChJ",
    education: "Oliy (TDIU, Moliya, 2021)",
    phone: '+998 9X XXX XX 13',
    lastUpdated: '2026-08-01',
    needsSupport: false,
    supportTypes: [],
    history: [
      { date: '2021-07-01', status: STATUS.EMPLOYED, note: "Kompaniyaga hisobchi sifatida ishga kirdi" },
      { date: '2024-01-01', status: STATUS.EMPLOYED, note: "Bosh hisobchi lavozimiga ko'tarildi" },
    ],
  },
  {
    id: 'Y014',
    fullName: 'Sotvoldiyeva Nargiza Toxirovna',
    age: 19,
    gender: 'female',
    mahalla: 'Olmazar',
    status: STATUS.NEEDS_CLARIFICATION,
    occupation: null,
    education: "Noma'lum",
    phone: '+998 9X XXX XX 14',
    lastUpdated: '2026-04-10',
    needsSupport: true,
    supportTypes: [SUPPORT_TYPES.CLARIFICATION],
    history: [
      { date: '2026-04-10', status: STATUS.NEEDS_CLARIFICATION, note: "Mahalla vakilidan ma'lumot talab qilinadi, uy tashrifi zarur" },
    ],
  },
  {
    id: 'Y015',
    fullName: 'Eshmatov Jahongir Rustamovich',
    age: 24,
    gender: 'male',
    mahalla: 'Yangi hayot',
    status: STATUS.EDUCATION,
    occupation: null,
    education: "Oliy (TATU, Magistratura, 1-kurs, Sun'iy intellekt)",
    phone: '+998 9X XXX XX 15',
    lastUpdated: '2026-09-01',
    needsSupport: false,
    supportTypes: [],
    history: [
      { date: '2024-06-01', status: STATUS.UNEMPLOYED, note: "Bakalavr darajasini oldi" },
      { date: '2024-09-01', status: STATUS.EDUCATION, note: "Magistraturaga qabul qilindi" },
    ],
  },
  {
    id: 'Y016',
    fullName: 'Ismoilova Barno Shermatovna',
    age: 25,
    gender: 'female',
    mahalla: "Bog'ishamol",
    status: STATUS.ENTREPRENEURSHIP,
    occupation: "Tikuvchilik ustaxonasi — shaxsiy biznes",
    education: "O'rta (Umumta'lim maktabi, 2019)",
    phone: '+998 9X XXX XX 16',
    lastUpdated: '2026-07-15',
    needsSupport: false,
    supportTypes: [],
    history: [
      { date: '2019-06-01', status: STATUS.UNEMPLOYED, note: "Maktabni tamomlab ishsiz" },
      { date: '2020-08-01', status: STATUS.ENTREPRENEURSHIP, note: "Tadbirkorlik markazining yordami bilan tikuvchilik boshladi" },
    ],
  },
  {
    id: 'Y017',
    fullName: 'Rajabov Muxammad Yusufovich',
    age: 21,
    gender: 'male',
    mahalla: 'Universitet',
    status: STATUS.UNEMPLOYED,
    occupation: null,
    education: "O'rta maxsus (Qurilish va arxitektura kolleji, 2025)",
    phone: '+998 9X XXX XX 17',
    lastUpdated: '2026-08-10',
    needsSupport: true,
    supportTypes: [SUPPORT_TYPES.EMPLOYMENT, SUPPORT_TYPES.VOCATIONAL],
    history: [
      { date: '2025-07-01', status: STATUS.UNEMPLOYED, note: "Kollejni tamomlab, qurilish sohasida ish qidirmoqda" },
    ],
  },
  {
    id: 'Y018',
    fullName: 'Tursunova Gulnora Baxriddinovna',
    age: 27,
    gender: 'female',
    mahalla: "Do'stlik",
    status: STATUS.EMPLOYED,
    occupation: "Matematika o'qituvchisi — 45-son maktab",
    education: "Oliy (UzMU, Matematika, 2021)",
    phone: '+998 9X XXX XX 18',
    lastUpdated: '2026-08-01',
    needsSupport: false,
    supportTypes: [],
    history: [
      { date: '2021-07-01', status: STATUS.UNEMPLOYED, note: "Universitetni tamomlab ishsiz" },
      { date: '2021-09-01', status: STATUS.EMPLOYED, note: "Maktabga matematika o'qituvchisi sifatida ishga kirdi" },
    ],
  },
  {
    id: 'Y019',
    fullName: "Holiqov Rustam Bahodir o'g'li",
    age: 23,
    gender: 'male',
    mahalla: 'Zarnigor',
    status: STATUS.NEET,
    occupation: null,
    education: "O'rta (Umumta'lim maktabi, 2021)",
    phone: '+998 9X XXX XX 19',
    lastUpdated: '2026-07-01',
    needsSupport: true,
    supportTypes: [SUPPORT_TYPES.EMPLOYMENT, SUPPORT_TYPES.PSYCHOLOGICAL, SUPPORT_TYPES.VOCATIONAL],
    history: [
      { date: '2021-06-01', status: STATUS.UNEMPLOYED, note: "Maktabni tamomlab" },
      { date: '2022-03-01', status: STATUS.EMPLOYED, note: "Vaqtincha quruvchi sifatida ishladi (mavsumiy)" },
      { date: '2023-01-01', status: STATUS.NEET, note: "Ish joyini yo'qotdi, faoliyat yo'q, psixologik yordam kerak" },
    ],
  },
  {
    id: 'Y020',
    fullName: "Matchonova Dilrabo Parviz qizi",
    age: 18,
    gender: 'female',
    mahalla: "Qo'yliq",
    status: STATUS.EDUCATION,
    occupation: null,
    education: "O'rta maxsus (Tibbiyot kolleji, 1-kurs)",
    phone: '+998 9X XXX XX 20',
    lastUpdated: '2026-09-05',
    needsSupport: false,
    supportTypes: [],
    history: [
      { date: '2026-09-01', status: STATUS.EDUCATION, note: "Tibbiyot kollejiga qabul qilindi" },
    ],
  },
  {
    id: 'Y021',
    fullName: 'Sultonov Asilbek Komilovich',
    age: 26,
    gender: 'male',
    mahalla: 'Olmazar',
    status: STATUS.EMPLOYED,
    occupation: "Yuk mashinasi haydovchisi — Tez Yetkazish MChJ",
    education: "O'rta (Umumta'lim maktabi, 2018)",
    phone: '+998 9X XXX XX 21',
    lastUpdated: '2026-08-08',
    needsSupport: false,
    supportTypes: [],
    history: [
      { date: '2018-06-01', status: STATUS.UNEMPLOYED, note: "Maktabni tamomlab ishsiz" },
      { date: '2019-05-01', status: STATUS.EMPLOYED, note: "Haydovchilik kursini tamomlab, logistika kompaniyasiga kirdi" },
    ],
  },
  {
    id: 'Y022',
    fullName: "Xasanova Kamola Ulug'bek qizi",
    age: 20,
    gender: 'female',
    mahalla: 'Yangi hayot',
    status: STATUS.UNEMPLOYED,
    occupation: null,
    education: "Oliy (TATU, 2-kurs, akademik ta'tilda)",
    phone: '+998 9X XXX XX 22',
    lastUpdated: '2026-06-20',
    needsSupport: true,
    supportTypes: [SUPPORT_TYPES.EMPLOYMENT],
    history: [
      { date: '2026-02-01', status: STATUS.EDUCATION, note: "Sog'liq sababi akademik ta'tilga chiqdi" },
      { date: '2026-06-20', status: STATUS.UNEMPLOYED, note: "Ta'til davrida vaqtincha ish qidiryapti" },
    ],
  },
  {
    id: 'Y023',
    fullName: 'Nurmatov Elbek Saidakbarovich',
    age: 29,
    gender: 'male',
    mahalla: "Bog'ishamol",
    status: STATUS.ENTREPRENEURSHIP,
    occupation: "Milliy taom kafeyi egasi",
    education: "O'rta maxsus (Oshpazlik kolleji, 2019)",
    phone: '+998 9X XXX XX 23',
    lastUpdated: '2026-08-05',
    needsSupport: false,
    supportTypes: [],
    history: [
      { date: '2019-07-01', status: STATUS.EMPLOYED, note: "Restoranda oshpaz sifatida ishladi" },
      { date: '2022-05-01', status: STATUS.ENTREPRENEURSHIP, note: "O'z kafeysini ochdi, 5 xodim bilan" },
    ],
  },
  {
    id: 'Y024',
    fullName: 'Botirov Zafar Normurodovich',
    age: 22,
    gender: 'male',
    mahalla: 'Universitet',
    status: STATUS.NEEDS_CLARIFICATION,
    occupation: null,
    education: "Noma'lum",
    phone: '+998 9X XXX XX 24',
    lastUpdated: '2026-03-15',
    needsSupport: true,
    supportTypes: [SUPPORT_TYPES.CLARIFICATION],
    history: [
      { date: '2026-03-15', status: STATUS.NEEDS_CLARIFICATION, note: "Aloqa o'rnatilmadi, uy manziliga tashrif zarur" },
    ],
  },
  {
    id: 'Y025',
    fullName: "Qodirov Sarvar Hayot o'g'li",
    age: 24,
    gender: 'male',
    mahalla: "Do'stlik",
    status: STATUS.EMPLOYED,
    occupation: "Grafik dizayner — Freelance (Upwork)",
    education: "Oliy (TDPU, San'at va dizayn, 2024)",
    phone: '+998 9X XXX XX 25',
    lastUpdated: '2026-08-12',
    needsSupport: false,
    supportTypes: [],
    history: [
      { date: '2024-07-01', status: STATUS.UNEMPLOYED, note: "Universitetni tamomlab, ish qidirdi" },
      { date: '2024-10-01', status: STATUS.EMPLOYED, note: "Xalqaro platforma orqali freelance faoliyat boshladi" },
    ],
  },
];

function computeStats() {
  const total = youthProfiles.length;
  const byStatus = {};
  const byMahalla = {};
  const byGender = { male: 0, female: 0 };

  youthProfiles.forEach((p) => {
    byStatus[p.status] = (byStatus[p.status] || 0) + 1;
    byMahalla[p.mahalla] = (byMahalla[p.mahalla] || 0) + 1;
    byGender[p.gender]++;
  });

  const needsSupport = youthProfiles.filter((p) => p.needsSupport).length;

  return {
    total,
    byStatus,
    byMahalla,
    byGender,
    needsSupport,
    neetCount: byStatus[STATUS.NEET] || 0,
    employedCount: byStatus[STATUS.EMPLOYED] || 0,
    unemployedCount: byStatus[STATUS.UNEMPLOYED] || 0,
    educationCount: byStatus[STATUS.EDUCATION] || 0,
    entrepreneurshipCount: byStatus[STATUS.ENTREPRENEURSHIP] || 0,
    needsClarificationCount: byStatus[STATUS.NEEDS_CLARIFICATION] || 0,
  };
}

module.exports = { youthProfiles, computeStats, STATUS, MAHALLAS, SUPPORT_TYPES };

